"""
TestFortge — Interactive QA Assistant (chatbot)

A small rule-based assistant that lives in the bottom-right corner of
every page. It plays two roles:

1. **Help-desk for end users** — answers "what is X?", "how do I X?",
   "where is X?" style questions about every TestFortge module
   (Estimation, Test Cases, Checklist, Test Execution, Automation QA,
   Bug Reports, credentials, site crawling, etc.).

2. **Requirement-clarifier for the generated QA Engineers** — when the
   user types a raw requirement or a vague request, the bot asks
   targeted clarification questions (domain, scope, roles, data,
   edge-cases) so the downstream generators have enough context to
   produce high-quality output.

The module is intentionally dependency-free and deterministic so the
tests can assert on the exact replies. Every reply has an EN and UA
counterpart; the caller passes ``lang`` explicitly.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Callable


# ═══════════════════════════════════════════════════════════════════
# Reply envelope
# ═══════════════════════════════════════════════════════════════════

@dataclass
class ChatReply:
    """One reply from the assistant."""
    text: str
    intent: str = "generic"
    suggestions: list[str] = field(default_factory=list)
    # When the bot is asking clarification questions it sets
    # ``follow_up`` so the UI can show them as quick-reply chips.
    follow_up: list[str] = field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════
# Small helpers
# ═══════════════════════════════════════════════════════════════════

_WORD = re.compile(r"\w+", re.UNICODE)

def _norm(text: str) -> str:
    return (text or "").strip().lower()


def _any(hay: str, needles: list[str]) -> bool:
    return any(n in hay for n in needles)


# ═══════════════════════════════════════════════════════════════════
# Knowledge: module-level help cards (EN + UA)
# ═══════════════════════════════════════════════════════════════════

_HELP_EN = {
    "estimation": (
        "**Estimation** is the QA Team Lead workspace. Paste requirements, "
        "upload a file, or give a URL — TestFortge crawls the site, extracts "
        "features and produces PERT-based hours using reference rates "
        "(5 min per TC, 0.3% compat rate, 15% bug-report overhead, etc.). "
        "Export the full breakdown as XLSX."
    ),
    "test_cases": (
        "**Test Cases** are generated by a Senior QA Engineer persona in "
        "TestFort format (SC1_001 grouped by section). Input can be free "
        "text, files (.docx, .pdf, .xlsx, .csv, .md, .txt) or a URL. "
        "Every user story yields positive + negative + edge-case coverage."
    ),
    "checklist": (
        "**Checklist** produces a low-level TestFort checklist (HDR_001, "
        "FTR_001…). Same inputs as Test Cases. Use it for quick regression "
        "sweeps or smoke passes."
    ),
    "test_execution": (
        "**Test Execution** runs selected test cases or checklist items "
        "against the resource URL (or simulates them). You pick the "
        "tester, environment (OS/browser/device/resolution), and testing "
        "types. If the flow needs login, fill in the Test Account card — "
        "or click 'Generate test account' to get a throw-away pair."
    ),
    "automation": (
        "**Automation QA** drives Playwright against the base URL. Choose "
        "headless or headed (headed slows actions so you can see clicks, "
        "scrolls and typing). Add Test Account credentials for login-gated "
        "flows; the runner can even auto-register if you give it a "
        "Registration URL."
    ),
    "bug_reports": (
        "**Bug Reports** stores the bugs produced during Test Execution "
        "or added manually. Severity + priority + environment are captured "
        "per bug; you can export the whole set as Markdown."
    ),
    "checkout_flow": (
        "A **Checkout Flow** is the end-to-end buyer journey: Discovery → "
        "Cart → Auth/Guest → Shipping → Payment → Review → Place Order → "
        "Confirmation, plus edge and security checks. TestFortge has a "
        "built-in playbook with ~45 mandatory checks. Just type "
        "'Create Checkout flow test cases for https://YOUR-SITE/' in the "
        "Test Cases screen and all of them are generated automatically."
    ),
    "credentials": (
        "The **Test Account** card on Test Execution and Automation QA "
        "has three modes: *No auth* (public pages), *Use existing account* "
        "(you type login/password), and *Generate test account* (TestFortge "
        "creates a throw-away pair; if you also supply a Registration "
        "URL, the automation runner can register the account for you)."
    ),
    "languages": (
        "TestFortge is bilingual. Click **EN** / **UA** at the top of the "
        "sidebar to switch — every label, hint and generated section title "
        "follows the selected language."
    ),
}

_HELP_UA = {
    "estimation": (
        "**Естімація** — робоче місце QA Team Lead. Вставте вимоги, "
        "завантажте файл або вкажіть URL — TestFortge прокраулить сайт, "
        "визначить функціонал та порахує години методом PERT за "
        "довідковими коефіцієнтами (5 хв на TC, 0,3% на платформу, "
        "15% на багрепорти тощо). Експорт у XLSX."
    ),
    "test_cases": (
        "**Test Cases** генеруються персоною Senior QA Engineer у форматі "
        "TestFort (SC1_001 за секціями). Джерело: текст, файл "
        "(.docx, .pdf, .xlsx, .csv, .md, .txt) або URL. Кожна історія "
        "отримує позитивні + негативні + граничні перевірки."
    ),
    "checklist": (
        "**Чек-ліст** формує TestFort-чеклист низького рівня (HDR_001, "
        "FTR_001…). Ті самі джерела, що й у Test Cases. Використовуйте "
        "для швидкого регресу або смоук-проходу."
    ),
    "test_execution": (
        "**Виконання тестів** запускає обрані тест-кейси чи пункти "
        "чек-ліста на URL ресурсу (або симулює їх). Оберіть тестувальника, "
        "оточення (ОС/браузер/пристрій/роздільну здатність), типи "
        "тестування. Якщо потрібен вхід — заповніть картку тестового "
        "акаунта або натисніть 'Згенерувати тестовий акаунт'."
    ),
    "automation": (
        "**Automation QA** керує Playwright на базовій URL. Обирайте "
        "headless чи вікно (у режимі вікна дії уповільнені, щоб ви бачили "
        "кліки, скрол і ввід). Додайте креденшіали Test Account для "
        "флоу з логіном; раннер уміє авто-реєструвати акаунт, якщо "
        "вказати Registration URL."
    ),
    "bug_reports": (
        "**Баг-репорти** зберігають баги з Test Execution або додані "
        "вручну. Severity + priority + environment фіксуються на кожен "
        "баг; можна експортувати увесь набір у Markdown."
    ),
    "checkout_flow": (
        "**Checkout flow** — наскрізний шлях покупця: Discovery → "
        "Кошик → Авторизація/Гість → Доставка → Оплата → Перегляд → "
        "Оформлення → Підтвердження, плюс граничні та безпекові перевірки. "
        "TestFortge має вбудований плейбук на ~45 обов'язкових перевірок. "
        "Введіть 'Create Checkout flow test cases for https://ВАШ-САЙТ/' "
        "на екрані Test Cases — усі вони згенеруються автоматично."
    ),
    "credentials": (
        "Картка **Test Account** у Test Execution та Automation QA має "
        "три режими: *Без авторизації*, *Використати існуючий акаунт* "
        "(ви вводите логін/пароль) і *Згенерувати тестовий акаунт* "
        "(TestFortge створює одноразову пару; якщо вказати Registration URL, "
        "раннер автоматизації сам зареєструє акаунт)."
    ),
    "languages": (
        "TestFortge підтримує дві мови. Натисніть **EN** / **UA** вгорі "
        "бічної панелі — усі підписи, підказки та розділи згенерованих "
        "артефактів підлаштуються під обрану мову."
    ),
}

# Synonyms → help card key (EN + UA). Order matters only within _HELP keys;
# the matcher checks each synonym group against the user's normalized
# lowercase message.
_MODULE_SYNONYMS = {
    "checkout_flow":  ["checkout flow", "checkout process", "purchase flow",
                       "buy flow", "order flow", "place order",
                       "оформлення замовлення", "процес покупки", "чекаут", "чек-аут"],
    "estimation":     ["estimation", "estimate", "hours", "pert", "естімаці",
                       "оцін", "годин", "пер"],
    "test_cases":     ["test case", "tc ", "tcs", "test-case",
                       "тест-кейс", "тесткейс", "кейс"],
    "checklist":      ["checklist", "чек-ліст", "чеклист"],
    "test_execution": ["test execution", "execution", "run test", "виконання тест",
                       "виконати тест"],
    "automation":     ["automation", "playwright", "headless", "browser automation",
                       "автомат", "хедлес"],
    "bug_reports":    ["bug report", "bug", "defect", "issue log",
                       "баг", "дефект", "помилк"],
    "credentials":    ["credential", "login", "password", "sign in",
                       "акаунт", "логін", "пароль"],
    "languages":      ["language", "translate", "ua", "english",
                       "мова", "переклад", "українськ", "англійськ"],
}


# ═══════════════════════════════════════════════════════════════════
# Intent patterns
# ═══════════════════════════════════════════════════════════════════

_GREETINGS = [
    "hi", "hello", "hey", "good morning", "good afternoon", "good evening",
    "привіт", "доброго дня", "добрий день", "вітаю", "йо",
]

_GRATITUDE = ["thanks", "thank you", "ty ", "дякую", "спасибі"]

_ASK_HELP_EN = ["help", "what can you do", "how do i", "how to", "where is",
                "what is", "explain", "guide"]
_ASK_HELP_UA = ["допомо", "що ти вмієш", "як", "де", "поясни", "що таке"]

_BROKEN_EN = ["error", "not working", "broken", "fails", "failed", "bug",
              "doesn't work", "doesn’t work", "cannot", "can't"]
_BROKEN_UA = ["помилк", "не працю", "зламан", "не вдається", "не можу"]

# Requirement-clarifier triggers — when the user tries to write a
# requirement / user story and we want to help them shape it.
_REQ_MARKERS_EN = ["as a ", "user can ", "user should ", "the system should",
                   "feature:", "requirement:"]
_REQ_MARKERS_UA = ["як ", "користувач має", "користувач може", "система має",
                   "вимога:", "функція:"]


# ═══════════════════════════════════════════════════════════════════
# Reply builders
# ═══════════════════════════════════════════════════════════════════

def _greeting(lang: str) -> ChatReply:
    if lang == "ua":
        return ChatReply(
            text=("Вітаю! Я QA-асистент TestFortge. Можу пояснити будь-який "
                  "модуль (Естімація, Test Cases, Checklist, Test Execution, "
                  "Automation QA, Bug Reports), підказати як працює Checkout "
                  "flow або допомогти сформулювати вимогу так, щоб згенеровані "
                  "QA Engineers її коректно зрозуміли."),
            intent="greeting",
            suggestions=[
                "Що таке Checkout flow?",
                "Як додати тестовий акаунт?",
                "Як працює Автоматизація?",
                "Допоможи сформулювати вимогу",
            ],
        )
    return ChatReply(
        text=("Hi! I'm the TestFortge assistant. I can explain any module "
              "(Estimation, Test Cases, Checklist, Test Execution, "
              "Automation QA, Bug Reports), walk you through the Checkout "
              "flow playbook, or help you phrase a requirement so the "
              "generated QA Engineers understand it correctly."),
        intent="greeting",
        suggestions=[
            "What is the Checkout flow?",
            "How do I add a test account?",
            "How does Automation work?",
            "Help me phrase a requirement",
        ],
    )


def _gratitude(lang: str) -> ChatReply:
    if lang == "ua":
        return ChatReply(
            text="Будь ласка! Якщо виникнуть питання — просто напишіть.",
            intent="gratitude",
        )
    return ChatReply(
        text="You're welcome! Ping me any time.",
        intent="gratitude",
    )


def _module_help(key: str, lang: str) -> ChatReply:
    cards = _HELP_UA if lang == "ua" else _HELP_EN
    text = cards.get(key, "")
    if not text:
        return _default_help(lang)
    suggestions = _related_suggestions(key, lang)
    return ChatReply(text=text, intent=f"help_{key}", suggestions=suggestions)


def _related_suggestions(key: str, lang: str) -> list[str]:
    if lang == "ua":
        base = {
            "estimation":     ["Експортувати оцінку в XLSX", "Які джерела підтримуються?"],
            "test_cases":     ["Що таке Checkout flow?", "Як додати файл вимог?"],
            "checklist":      ["Різниця між чек-лістом і тест-кейсами", "Як запустити виконання?"],
            "test_execution": ["Як додати тестовий акаунт?", "Які типи тестування обрати?"],
            "automation":     ["Як увімкнути headed-режим?", "Як налаштувати авто-реєстрацію?"],
            "bug_reports":    ["Експорт багів у Markdown", "Як пов'язати баг з тест-кейсом?"],
            "checkout_flow": ["Які фази перевіряються?", "Який шаблон тест-карти для Checkout?"],
            "credentials":    ["Згенерувати тестовий акаунт", "Як пройти 2FA у Playwright?"],
        }
        return base.get(key, ["Що таке TestFortge?"])
    base = {
        "estimation":     ["Export estimation to XLSX", "What sources are supported?"],
        "test_cases":     ["What is the Checkout flow?", "How do I upload a spec?"],
        "checklist":      ["Checklist vs Test Cases", "How do I run execution?"],
        "test_execution": ["How do I add a test account?", "Which testing types to pick?"],
        "automation":     ["Turn on headed mode", "Auto-register new accounts"],
        "bug_reports":    ["Export bugs to Markdown", "Link a bug to a test case"],
        "checkout_flow": ["Which phases are covered?", "Show me the card data I can use"],
        "credentials":    ["Generate a throw-away account", "How to pass 2FA in Playwright?"],
    }
    return base.get(key, ["What is TestFortge?"])


def _default_help(lang: str) -> ChatReply:
    if lang == "ua":
        return ChatReply(
            text=("Я вмію: пояснити кожен модуль, показати перевірки для "
                  "Checkout flow, допомогти сформулювати вимогу, підказати "
                  "як додати тестовий акаунт. Про який модуль розповісти?"),
            intent="help_menu",
            suggestions=["Естімація", "Test Cases", "Чек-ліст", "Test Execution",
                         "Automation QA", "Bug Reports", "Checkout flow"],
        )
    return ChatReply(
        text=("I can explain each module, walk through the Checkout flow "
              "checks, help you phrase a requirement, or show how to set up "
              "a test account. Which module should I start with?"),
        intent="help_menu",
        suggestions=["Estimation", "Test Cases", "Checklist", "Test Execution",
                     "Automation QA", "Bug Reports", "Checkout flow"],
    )


def _troubleshoot(lang: str, user_msg: str) -> ChatReply:
    low = _norm(user_msg)
    if "automation" in low or "playwright" in low or "автомат" in low:
        if lang == "ua":
            return ChatReply(
                text=("Часті причини збоїв Automation QA: 1) сторінка "
                      "потребує входу — додайте Test Account; 2) headless "
                      "режим пропускає капчу — перемкніть на 'No (показати "
                      "браузер)'; 3) селектор не знайдено — увімкніть "
                      "'Advanced: custom selectors' і вкажіть точні поля."),
                intent="troubleshoot_automation",
            )
        return ChatReply(
            text=("Common Automation QA failures: 1) page requires login — "
                  "fill the Test Account card; 2) headless hits a captcha — "
                  "switch to 'No (show browser)'; 3) selector not found — "
                  "open 'Advanced: custom selectors' and pass exact fields."),
            intent="troubleshoot_automation",
        )
    if "crawl" in low or "прокраул" in low or "site" in low:
        if lang == "ua":
            return ChatReply(
                text=("Якщо краулер не дістається потрібних сторінок: "
                      "додайте Test Account (сайт під логіном), або вставте "
                      "прямі URL у текстове поле вимог, або завантажте "
                      "sitemap/spec-файл."),
                intent="troubleshoot_crawl",
            )
        return ChatReply(
            text=("If the crawler can't reach internal pages: add a Test "
                  "Account (site behind login), paste direct URLs into the "
                  "requirements textarea, or upload a sitemap/spec file."),
            intent="troubleshoot_crawl",
        )
    if lang == "ua":
        return ChatReply(
            text=("Опишіть, що саме не працює: який модуль, який крок, "
                  "яке повідомлення з'явилось? Я підкажу наступний крок."),
            intent="troubleshoot_generic",
            follow_up=["Який модуль?", "Який саме крок?", "Текст помилки?"],
        )
    return ChatReply(
        text=("Tell me what's broken: which module, which step, and the "
              "error text you saw. I'll suggest the next move."),
        intent="troubleshoot_generic",
        follow_up=["Which module?", "Which step?", "Error text?"],
    )


def _clarify_requirement(lang: str, text: str) -> ChatReply:
    """Ask targeted questions to turn a vague requirement into testable input."""
    if lang == "ua":
        return ChatReply(
            text=("Щоб згенерувати якісні тест-кейси, мені треба ще кілька "
                  "деталей. Дайте відповідь на ці запитання:"),
            intent="clarify_requirement",
            follow_up=[
                "Хто користувач (роль)?",
                "Яка мета цієї дії?",
                "Які вхідні дані / формати?",
                "Які очікувані обмеження (межі, формат, кількість)?",
                "Як виглядає успіх? А помилка?",
                "Чи потрібна авторизація?",
                "Чи є залежні інтеграції (пошта, платіж, API)?",
            ],
        )
    return ChatReply(
        text=("To generate strong test cases I need a few more details. "
              "Please answer these:"),
        intent="clarify_requirement",
        follow_up=[
            "Who is the user (role)?",
            "What is the goal of this action?",
            "What inputs / formats are used?",
            "What limits apply (ranges, format, count)?",
            "What does success look like? And failure?",
            "Is authentication required?",
            "Are there dependent integrations (email, payment, API)?",
        ],
    )


def _checkout_flow_details(lang: str) -> ChatReply:
    """Show a short list of the 9 phases so the user sees the scope."""
    try:
        from .knowledge_base import FLOW_PLAYBOOKS
        phases = [p["phase"] for p in FLOW_PLAYBOOKS["checkout_flow"]["required_phases"]]
    except Exception:
        phases = ["Discovery / Product", "Cart", "Authentication / Guest",
                  "Shipping & Contact", "Payment", "Review & Place Order",
                  "Confirmation & Post-order", "Edge / Negative",
                  "Security & Compliance"]

    if lang == "ua":
        text = ("Плейбук Checkout flow у TestFortge покриває такі фази:\n- " +
                "\n- ".join(phases) +
                "\n\nУсього ~45 обов'язкових перевірок. Щоб згенерувати, "
                "введіть у Test Cases: 'Create Checkout flow test cases for "
                "https://ВАШ-САЙТ/'.")
        sugg = ["Які тестові дані використати?", "Як додати тестовий акаунт?"]
    else:
        text = ("The TestFortge Checkout flow playbook covers:\n- " +
                "\n- ".join(phases) +
                "\n\n~45 mandatory checks in total. To generate, type in "
                "Test Cases: 'Create Checkout flow test cases for "
                "https://YOUR-SITE/'.")
        sugg = ["Which test data to use?", "How do I add a test account?"]
    return ChatReply(text=text, intent="help_checkout_flow", suggestions=sugg)


# ═══════════════════════════════════════════════════════════════════
# Main dispatch
# ═══════════════════════════════════════════════════════════════════

def respond(message: str, lang: str = "en") -> ChatReply:
    """Produce a :class:`ChatReply` for ``message``.

    The dispatcher is a cascade of cheap checks — greeting → gratitude →
    troubleshooting → flow help → per-module help → requirement
    clarification → default. The logic is intentionally conservative so
    replies stay predictable and tests can assert them.
    """
    raw = (message or "").strip()
    low = _norm(raw)
    if not low:
        return _default_help(lang)

    # Greeting / gratitude (fast path)
    if _any(low, _GREETINGS) and len(low) < 40:
        return _greeting(lang)
    if _any(low, _GRATITUDE):
        return _gratitude(lang)

    # Troubleshooting intent — anything that sounds like a failure
    if _any(low, _BROKEN_EN) or _any(low, _BROKEN_UA):
        return _troubleshoot(lang, raw)

    # Checkout-flow specific — always surface the playbook
    if _any(low, _MODULE_SYNONYMS["checkout_flow"]):
        # If the user asked for phases / steps / checks — show the list
        if _any(low, ["phase", "step", "list", "which", "what check",
                      "фаз", "кроки", "перевірк", "які"]):
            return _checkout_flow_details(lang)
        return _module_help("checkout_flow", lang)

    # Module-specific help
    for key, syns in _MODULE_SYNONYMS.items():
        if key == "checkout_flow":
            continue  # already handled above
        if _any(low, syns):
            return _module_help(key, lang)

    # Requirement shaping: user pasted something that looks like a story
    if _any(low, _REQ_MARKERS_EN) or _any(low, _REQ_MARKERS_UA):
        return _clarify_requirement(lang, raw)

    # "What can you do" / generic help
    if _any(low, _ASK_HELP_EN) or _any(low, _ASK_HELP_UA):
        return _default_help(lang)

    # Last resort — treat as a requirement that needs clarification
    return _clarify_requirement(lang, raw)


def respond_dict(message: str, lang: str = "en") -> dict:
    """JSON-ready wrapper used by the Flask route."""
    r = respond(message, lang)
    return {
        "text": r.text,
        "intent": r.intent,
        "suggestions": r.suggestions,
        "follow_up": r.follow_up,
    }
