"""
TestFortge — Export Module

Exports all generated artifacts to:
  - Markdown (.md)
  - HTML (.html) — standalone, printable
  - CSV (.csv) — test cases & checklists
"""

import csv
import io
import html as html_mod
from datetime import date

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

from .user_story_generator import UserStory
from .testcase_generator import TestCase, ChecklistItem


def export_markdown(project_name: str, stories: list[UserStory],
                    test_cases: list[TestCase], checklist: list[ChecklistItem],
                    traceability: list[dict], recommendations: dict) -> str:
    lines: list[str] = []
    a = lines.append

    a(f"# TestFortge — Test Documentation")
    a(f"## Project: {project_name}")
    a(f"\n**Generated:** {date.today().isoformat()}  ")
    a(f"**User Stories:** {len(stories)} | **Test Cases:** {len(test_cases)} | **Checklist Items:** {len(checklist)}\n")

    # User Stories
    a("---\n## 1. User Stories\n")
    for s in stories:
        a(f"### {s.id} (from {s.requirement_id})")
        a(f"**As a** {s.role}, **I want** {s.action}, **so that** {s.benefit}.\n")
        a(f"- **Priority:** {s.priority} | **Story Points:** {s.story_points_hint}")
        a(f"- **Acceptance Criteria:**")
        for ac in s.acceptance_criteria:
            a(f"  - [ ] {ac}")
        a("")

    # Test Cases
    a("---\n## 2. Test Cases\n")
    current_section = ""
    for tc in test_cases:
        if tc.section != current_section:
            current_section = tc.section
            a(f"\n### Section {tc.section_num}: {tc.section}\n")
        a(f"#### {tc.id}: {tc.summary}")
        a(f"- **User Story:** {tc.user_story_id} | **Category:** {tc.category} | **Priority:** {tc.priority}")
        a(f"- **Preconditions:** {tc.preconditions}")
        a(f"- **Test Steps:** {tc.test_steps}")
        a(f"- **Test Data:** {tc.test_data}")
        a(f"- **Expected Result:** {tc.expected_result}")
        if tc.issues:
            a(f"- **Issues:** {tc.issues}")
        if tc.comment:
            a(f"- **Comment:** {tc.comment}")
        a("")

    # Checklist
    if checklist:
        a("---\n## 3. Checklist\n")
        a("| ID | Section | Objective | Category | Priority | Status | Comments |")
        a("|----|---------|-----------|----------|----------|--------|----------|")
        for cl in checklist:
            a(f"| {cl.id} | {cl.section} | {cl.objective} | {cl.category} | {cl.priority} | {cl.status} | {cl.comments} |")
        a("")

    # Traceability
    a("---\n## 4. Traceability Matrix\n")
    a("| Requirement | User Story | Priority | Test Cases | Categories |")
    a("|-------------|------------|----------|------------|------------|")
    for row in traceability:
        tc_ids = ", ".join(row["test_case_ids"])
        cats = ", ".join(row["categories"])
        a(f"| {row['requirement_id']} | {row['user_story_id']} | {row['priority']} | {tc_ids} | {cats} |")
    a("")

    # Recommendations summary
    if recommendations.get("techniques"):
        a("---\n## 5. Recommended Test Design Techniques\n")
        for tech in recommendations["techniques"]:
            a(f"### {tech['name']} ({tech['category']})")
            a(f"{tech['description']}\n")
            a(f"**Relevance:** {tech.get('reasoning', '')}\n")

    if recommendations.get("testing_types"):
        a("---\n## 6. Recommended Testing Types\n")
        for tt in recommendations["testing_types"]:
            a(f"- **{tt['name']}** [{tt['priority']}]: {tt['reasoning']}")
        a("")

    if recommendations.get("standards"):
        a("---\n## 7. Applicable Standards\n")
        for std in recommendations["standards"]:
            a(f"- **{std['name']}** ({std['full_name']}): {std['relevance']}")
        a("")

    a(f"\n---\n*Generated by TestFortge on {date.today().isoformat()}*")
    return "\n".join(lines)


def export_html(project_name: str, stories: list[UserStory],
                test_cases: list[TestCase], checklist: list[ChecklistItem],
                traceability: list[dict], recommendations: dict) -> str:
    h = html_mod.escape
    p: list[str] = []
    a = p.append

    a("<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>")
    a(f"<title>TestFortge — {h(project_name)}</title>")
    a("<style>")
    a("""
body{font-family:'Segoe UI',system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#1e293b;line-height:1.6}
h1{color:#0f172a;border-bottom:3px solid #6366f1;padding-bottom:.5rem}
h2{color:#4338ca;margin-top:2rem;border-bottom:1px solid #e2e8f0;padding-bottom:.3rem}
h3{color:#1e3a5f;margin-top:1.2rem}
table{width:100%;border-collapse:collapse;margin:.75rem 0;font-size:.88rem}
th,td{border:1px solid #cbd5e1;padding:.5rem .7rem;text-align:left}
th{background:#4338ca;color:#fff;font-weight:600}
tr:nth-child(even){background:#f8fafc}
.badge{display:inline-block;padding:2px 10px;border-radius:12px;font-size:.78rem;font-weight:600}
.b-high{background:#fee2e2;color:#991b1b}.b-medium{background:#fef3c7;color:#92400e}.b-low{background:#d1fae5;color:#065f46}
.b-positive{background:#d1fae5;color:#065f46}.b-negative{background:#fee2e2;color:#991b1b}
.b-edge{background:#e0e7ff;color:#3730a3}.b-security{background:#fce7f3;color:#9d174d}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:1.2rem;margin:1rem 0;box-shadow:0 1px 3px rgba(0,0,0,.06)}
.story-card{border-left:4px solid #6366f1}
.tc-card{border-left:4px solid #2563eb}
.meta{color:#64748b;font-size:.85rem}
ul{margin:.5rem 0;padding-left:1.5rem}
@media print{body{font-size:10pt}h1{border-color:#000}.card{box-shadow:none;break-inside:avoid}}
""")
    a("</style></head><body>")
    a(f"<h1>TestFortge &mdash; {h(project_name)}</h1>")
    a(f"<p class='meta'>Generated: {date.today().isoformat()} &middot; "
      f"{len(stories)} stories &middot; {len(test_cases)} test cases &middot; {len(checklist)} checklist items</p>")

    # Stories
    a("<h2>1. User Stories</h2>")
    for s in stories:
        pcls = f"b-{s.priority.lower()}"
        a(f"<div class='card story-card'><h3>{h(s.id)} <span class='badge {pcls}'>{h(s.priority)}</span>"
          f" <span class='meta'>from {h(s.requirement_id)} &middot; ~{h(s.story_points_hint)} SP</span></h3>")
        a(f"<p><strong>As a</strong> {h(s.role)}, <strong>I want</strong> {h(s.action)}, "
          f"<strong>so that</strong> {h(s.benefit)}.</p>")
        a("<p><strong>Acceptance Criteria:</strong></p><ul>")
        for ac in s.acceptance_criteria:
            a(f"<li>{h(ac)}</li>")
        a("</ul></div>")

    # Test Cases
    a("<h2>2. Test Cases</h2>")
    current_section = ""
    for tc in test_cases:
        if tc.section != current_section:
            current_section = tc.section
            a(f"<h3>Section {tc.section_num}: {h(tc.section)}</h3>")
        ccls = f"b-{tc.category.lower().replace(' ', '-').replace('edge-case','edge')}"
        pcls = f"b-{tc.priority.lower()}"
        a(f"<div class='card tc-card'><h3>{h(tc.id)}: {h(tc.summary)} "
          f"<span class='badge {ccls}'>{h(tc.category)}</span> "
          f"<span class='badge {pcls}'>{h(tc.priority)}</span></h3>")
        a(f"<p class='meta'>Story: {h(tc.user_story_id)}</p>")
        a("<table>")
        a(f"<tr><th>Preconditions</th><td>{h(tc.preconditions)}</td></tr>")
        a(f"<tr><th>Test Steps</th><td>{h(tc.test_steps)}</td></tr>")
        a(f"<tr><th>Test Data</th><td>{h(tc.test_data)}</td></tr>")
        a(f"<tr><th>Expected Result</th><td>{h(tc.expected_result)}</td></tr>")
        a(f"<tr><th>Issues</th><td>{h(tc.issues or '—')}</td></tr>")
        a(f"<tr><th>Comment</th><td>{h(tc.comment or '—')}</td></tr>")
        a("</table></div>")

    # Checklist
    if checklist:
        a("<h2>3. Checklist</h2><table>")
        a("<tr><th>ID</th><th>Section</th><th>Objective</th><th>Category</th><th>Priority</th><th>Status</th><th>Comments</th></tr>")
        for cl in checklist:
            a(f"<tr><td>{h(cl.id)}</td><td>{h(cl.section)}</td><td>{h(cl.objective)}</td>"
              f"<td>{h(cl.category)}</td><td>{h(cl.priority)}</td><td>{h(cl.status)}</td><td>{h(cl.comments)}</td></tr>")
        a("</table>")

    # Traceability
    a("<h2>4. Traceability Matrix</h2><table>")
    a("<tr><th>Requirement</th><th>User Story</th><th>Priority</th><th>Test Cases</th><th>Categories</th></tr>")
    for row in traceability:
        tc_ids = ", ".join(row["test_case_ids"])
        cats = ", ".join(row["categories"])
        a(f"<tr><td><b>{h(row['requirement_id'])}</b></td><td>{h(row['user_story_id'])}</td>"
          f"<td>{h(row['priority'])}</td><td>{h(tc_ids)}</td><td>{h(cats)}</td></tr>")
    a("</table>")

    a(f"<hr><p class='meta'>Generated by TestFortge on {date.today().isoformat()}</p>")
    a("</body></html>")
    return "\n".join(p)


def export_csv_testcases(test_cases: list[TestCase]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["TC ID", "Section", "Summary", "User Story", "Category", "Priority",
                "Preconditions", "Test Steps", "Test Data", "Expected Result", "Issues", "Comment", "Status"])
    for tc in test_cases:
        w.writerow([tc.id, tc.section, tc.summary, tc.user_story_id, tc.category, tc.priority,
                     tc.preconditions, tc.test_steps, tc.test_data, tc.expected_result,
                     tc.issues, tc.comment, tc.status])
    return buf.getvalue()


def export_csv_checklist(checklist: list[ChecklistItem]) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["ID", "Section", "Objective", "Category", "Priority", "Status", "Comments"])
    for cl in checklist:
        w.writerow([cl.id, cl.section, cl.objective, cl.category, cl.priority, cl.status, cl.comments])
    return buf.getvalue()


# ── XLSX helpers ──────────────────────────────────────────────────

_THIN_BORDER = Border(
    left=Side(style="thin", color="CBD5E1"),
    right=Side(style="thin", color="CBD5E1"),
    top=Side(style="thin", color="CBD5E1"),
    bottom=Side(style="thin", color="CBD5E1"),
)

_HEADER_FONT = Font(bold=True, color="FFFFFF", size=11)
_HEADER_FILL = PatternFill(start_color="4338CA", end_color="4338CA", fill_type="solid")
_HEADER_ALIGNMENT = Alignment(horizontal="center", vertical="center", wrap_text=True)

_ALT_ROW_FILL = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")

_PRIORITY_FILLS = {
    "High":   PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid"),
    "Medium": PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid"),
    "Low":    PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid"),
}

_CATEGORY_FILLS = {
    "Positive":  PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid"),
    "Negative":  PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid"),
    "Edge Case": PatternFill(start_color="E0E7FF", end_color="E0E7FF", fill_type="solid"),
    "Security":  PatternFill(start_color="FCE7F3", end_color="FCE7F3", fill_type="solid"),
}

_STATUS_FILLS = {
    "Passed":    PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid"),
    "Failed":    PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid"),
    "Passed but": PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid"),
    "Blocked":   PatternFill(start_color="E0E7FF", end_color="E0E7FF", fill_type="solid"),
    "Unchecked": PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid"),
}

_WRAP_ALIGNMENT = Alignment(vertical="top", wrap_text=True)
_DEFAULT_ALIGNMENT = Alignment(vertical="top")


def _apply_header_row(ws, headers: list[str]) -> None:
    """Write header row with indigo background and bold white text."""
    for col_idx, title in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx, value=title)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = _HEADER_ALIGNMENT
        cell.border = _THIN_BORDER


def _auto_column_widths(ws, headers: list[str], min_width: int = 10,
                        max_width: int = 50) -> None:
    """Set column widths based on header length and cell content."""
    for col_idx, header in enumerate(headers, start=1):
        longest = len(header)
        for row in ws.iter_rows(min_row=2, min_col=col_idx,
                                max_col=col_idx, values_only=True):
            val = str(row[0]) if row[0] is not None else ""
            # For multi-line values, use the longest single line
            line_max = max((len(line) for line in val.split("\n")), default=0)
            longest = max(longest, line_max)
        width = max(min_width, min(longest + 3, max_width))
        ws.column_dimensions[ws.cell(row=1, column=col_idx).column_letter].width = width


def _save_workbook_to_bytes(wb: Workbook) -> bytes:
    """Serialize a workbook to bytes via BytesIO."""
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()


# ── XLSX export — test cases ─────────────────────────────────────

def export_xlsx_testcases(test_cases: list[TestCase]) -> bytes:
    """Create a formatted XLSX workbook for test cases and return as bytes."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Test Cases"

    headers = [
        "TC ID", "Section", "Summary", "User Story", "Category", "Priority",
        "Preconditions", "Test Steps", "Test Data", "Expected Result",
        "Issues", "Comment", "Status",
    ]

    # Column indices (1-based) for special formatting
    col_category = 5
    col_priority = 6
    col_steps = 8
    col_expected = 10
    col_status = 13

    _apply_header_row(ws, headers)

    for row_idx, tc in enumerate(test_cases, start=2):
        values = [
            tc.id, tc.section, tc.summary, tc.user_story_id,
            tc.category, tc.priority, tc.preconditions, tc.test_steps,
            tc.test_data, tc.expected_result, tc.issues, tc.comment,
            tc.status,
        ]
        is_alt = (row_idx % 2 == 0)

        for col_idx, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.border = _THIN_BORDER

            # Wrap text for long-form columns
            if col_idx in (col_steps, col_expected):
                cell.alignment = _WRAP_ALIGNMENT
            else:
                cell.alignment = _DEFAULT_ALIGNMENT

            # Alternate row background (applied first; overridden below for
            # colored columns)
            if is_alt:
                cell.fill = _ALT_ROW_FILL

            # Priority coloring
            if col_idx == col_priority:
                fill = _PRIORITY_FILLS.get(val)
                if fill:
                    cell.fill = fill

            # Category coloring
            if col_idx == col_category:
                fill = _CATEGORY_FILLS.get(val)
                if fill:
                    cell.fill = fill

            # Status coloring
            if col_idx == col_status:
                fill = _STATUS_FILLS.get(val)
                if fill:
                    cell.fill = fill

    _auto_column_widths(ws, headers)
    ws.freeze_panes = "A2"

    return _save_workbook_to_bytes(wb)


# ── XLSX export — checklist ──────────────────────────────────────

def export_xlsx_checklist(checklist: list[ChecklistItem]) -> bytes:
    """Create a formatted XLSX workbook for checklist items and return as bytes."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Checklist"

    headers = ["ID", "Section", "Objective", "Category", "Priority", "Status", "Comments"]

    col_category = 4
    col_priority = 5
    col_status = 6

    _apply_header_row(ws, headers)

    for row_idx, cl in enumerate(checklist, start=2):
        values = [
            cl.id, cl.section, cl.objective, cl.category,
            cl.priority, cl.status, cl.comments,
        ]
        is_alt = (row_idx % 2 == 0)

        for col_idx, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.border = _THIN_BORDER
            cell.alignment = _DEFAULT_ALIGNMENT

            if is_alt:
                cell.fill = _ALT_ROW_FILL

            if col_idx == col_priority:
                fill = _PRIORITY_FILLS.get(val)
                if fill:
                    cell.fill = fill

            if col_idx == col_category:
                fill = _CATEGORY_FILLS.get(val)
                if fill:
                    cell.fill = fill

            if col_idx == col_status:
                fill = _STATUS_FILLS.get(val)
                if fill:
                    cell.fill = fill

    _auto_column_widths(ws, headers)
    ws.freeze_panes = "A2"

    return _save_workbook_to_bytes(wb)
