"""
TestFortge — Test Case & Checklist Generator (TestFort Template)

TestFort Test Case format:
  №  | Summary | Preconditions | Test Steps | Test Data | Expected Result | Issues | Comment
  SC1_001, SC1_002... grouped by Sections

TestFort Checklist format:
  #  | Objective | Comments/Issues
  HDR_001, FTR_001... grouped by Sections with prefix IDs

Statuses: Passed | Failed | Passed but | Blocked | Unchecked

Covers: Positive, Negative, Edge/Boundary cases.
"""

from dataclasses import dataclass, field
from .user_story_generator import UserStory


@dataclass
class TestCase:
    id: str               # SC1_001 format
    section: str           # Section name (e.g. "Header", "Login")
    section_num: int       # Section number
    summary: str           # Test case summary
    preconditions: str     # Preconditions if needed
    test_steps: str        # Numbered steps: "1. Step\n2. Step..."
    test_data: str         # Test data if needed
    expected_result: str   # Expected behavior description
    issues: str = ""       # Issue references
    comment: str = ""      # Additional info
    user_story_id: str = ""
    category: str = ""     # Positive / Negative / Edge Case / Security
    priority: str = "Medium"
    status: str = "Unchecked"  # Passed / Failed / Passed but / Blocked / Unchecked
    # Dominant testing-type label (Functional / Smoke / Regression /
    # Performance / Security / Accessibility / Usability / SEO /
    # Localization / Compatibility / API / E&E / Exploratory).
    # Defaults to Functional for cases generated by older paths.
    testing_type: str = "Functional"


@dataclass
class ChecklistItem:
    id: str               # HDR_001, FTR_001 format
    section: str           # Section name
    objective: str         # Summary of the checklist item
    comments: str = ""     # Comments / Issues
    user_story_id: str = ""
    category: str = ""     # Positive / Negative / Edge Case
    priority: str = "Medium"
    status: str = "Unchecked"
    testing_type: str = "Functional"  # see TestCase.testing_type


# ── Section prefix mapping ──────────────────────────────────────

_SECTION_PREFIXES = {
    "auth": ("AUTH", "Authentication"),
    "crud_create": ("CRT", "Create / Add"),
    "crud_read": ("VIEW", "View / Display"),
    "crud_update": ("UPD", "Edit / Update"),
    "crud_delete": ("DEL", "Delete / Remove"),
    "search": ("SRCH", "Search / Filter"),
    "payment": ("PAY", "Payment / Checkout"),
    "upload": ("UPL", "Upload / Import"),
    "export": ("EXP", "Export / Download"),
    "notification": ("NTF", "Notifications"),
    "security": ("SEC", "Security"),
    "performance": ("PERF", "Performance"),
    "integration": ("API", "API / Integration"),
    "navigation": ("NAV", "Navigation"),
    "profile": ("PROF", "Profile / Settings"),
    "generic": ("GEN", "General"),
}

# ── Keyword-based scenario detection ────────────────────────────

_SCENARIO_KEYWORDS = {
    "auth": ["login", "register", "sign up", "sign in", "password", "authentication",
             "logout", "session", "credential", "2fa", "mfa"],
    "crud_create": ["create", "add", "new", "register", "insert", "submit"],
    "crud_read": ["view", "display", "show", "list", "read", "get", "dashboard", "report"],
    "crud_update": ["edit", "update", "modify", "change", "save"],
    "crud_delete": ["delete", "remove", "cancel", "deactivate"],
    "search": ["search", "find", "filter", "sort", "query", "lookup"],
    "payment": ["payment", "pay", "checkout", "billing", "transaction", "purchase", "order"],
    "upload": ["upload", "import", "attach", "file"],
    "export": ["export", "download", "report", "csv", "pdf"],
    "notification": ["notification", "notify", "alert", "email", "sms", "push"],
    "security": ["encrypt", "permission", "role", "access", "authorize", "protect"],
    "performance": ["performance", "load", "speed", "fast", "response time", "scalab"],
    "integration": ["api", "integrate", "third-party", "webhook", "endpoint"],
}


def _detect_scenario(text: str) -> str:
    lower = text.lower()
    for scenario, keywords in _SCENARIO_KEYWORDS.items():
        if any(kw in lower for kw in keywords):
            return scenario
    return "generic"


def _short(text: str, maxlen: int = 80) -> str:
    text = text.strip().rstrip(".")
    return text if len(text) <= maxlen else text[:maxlen - 3] + "..."


# ── Test Case generators per scenario ───────────────────────────

def _make_tc(section_num: int, idx: int, section: str, prefix: str,
             story: UserStory, category: str, summary: str, preconditions: str,
             steps: list[str], test_data: str, expected: str, comment: str = "") -> TestCase:
    tc_id = f"SC{section_num}_{idx:03d}"
    steps_text = "\n".join(f"{i+1}. {s}" for i, s in enumerate(steps))
    return TestCase(
        id=tc_id, section=section, section_num=section_num,
        summary=summary, preconditions=preconditions,
        test_steps=steps_text, test_data=test_data,
        expected_result=expected, comment=comment,
        user_story_id=story.id, category=category, priority=story.priority,
    )


def _auth_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["auth"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Log in with a valid account and confirm the session opens ({action})",
        "Application is reachable. A pre-registered test account exists with a known password.",
        ["Open the application base URL in the browser",
         "Click the Sign In / Login link in the Header",
         "Enter the registered email into the email field",
         "Enter the matching password into the password field",
         "Click the Submit button",
         "Observe the URL and any authenticated UI elements that appear"],
        "Valid email: existing registered address. Password: the one set for that account.",
        "The URL changes to the post-login page (dashboard / account). Session cookie is set. The Header shows the user menu instead of the Sign In link. No error banner is rendered."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Attempt login with a non-matching password and confirm the attempt is rejected ({action})",
        "Application is reachable. Login page is opened.",
        ["Enter a registered email into the email field",
         "Enter a password that does not match the stored hash",
         "Click the Submit button",
         "Inspect the response body and any visible error banner"],
        "Email: valid registered address. Password: deliberately wrong value, e.g. wrong-pass-123.",
        "The URL stays on the login page. An error banner states the login was refused. The response body does not disclose whether the email or the password was the failing field. No session cookie is issued."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Submit the login form with missing fields and confirm client-side validation fires ({action})",
        "Application is reachable. Login page is opened.",
        ["Leave both the email and the password fields empty and click Submit",
         "Enter only the email, leave the password empty, then click Submit",
         "Clear the email, enter only the password, then click Submit"],
        "",
        "In each case the form does not issue a network request; the empty field is highlighted and an inline validation message identifies which field is required. The login page URL is unchanged."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Security",
        f"Probe the login form for brute-force throttling and injection handling ({action})",
        "Application is reachable. Login page is opened. Rate-limit window is reset for the test account.",
        ["Submit the login form six times in a row with a wrong password for the same email",
         "Observe whether the next attempt shows a lockout message or a CAPTCHA challenge",
         "Enter the SQL-injection payload into the email field and click Submit",
         "Enter the XSS payload into the email field and click Submit",
         "Open DevTools → Network and inspect the response for each attempt"],
        "SQL payload: ' OR 1=1 --  |  XSS payload: <script>alert(1)</script>",
        "After the throttling threshold the server responds with 429 or a CAPTCHA is rendered. The SQL payload is stored as literal text; no server-side error (500) is returned. The XSS payload is escaped in the DOM and the alert does not fire."))
    idx[0] += 1

    return cases


def _crud_create_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["crud_create"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Submit the creation form with valid data and confirm the record is persisted ({action})",
        "User is authenticated. Creation form route is reachable from the menu.",
        ["Click the Create / New / Add button in the list view",
         "Enter valid values into each required field in the form",
         "Click the Save button",
         "Open the list view again and locate the newly created row",
         "Click the row to open the detail view and compare each field with the submitted values"],
        "Valid data for every required field (respecting stated min/max lengths).",
        "The POST request returns HTTP 200 or 201 with a record id. A success toast is rendered. The list view shows the new row at the expected position, and the detail view displays the exact submitted values."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Submit the creation form with empty or malformed input and confirm the server rejects it ({action})",
        "User is authenticated. Creation form is opened.",
        ["Leave every required field empty and click Save",
         "Enter an email without an @ sign into an email field",
         "Enter letters into a numeric field",
         "Click Save after each mutation and inspect the response in DevTools → Network"],
        "Empty value, malformed email: notvalid, letters in a numeric field: abc.",
        "The server returns HTTP 400 / 422 or client-side validation blocks the request. No new record appears in the list view. Each failing field is highlighted with an inline message identifying the rule that was violated."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Test boundary lengths, Unicode payloads, and duplicate submission for {action}",
        "User is authenticated. Creation form is opened.",
        ["Enter a single-character value into each text field and click Save",
         "Enter a value at the documented maximum length into each text field and click Save",
         "Enter Unicode and emoji characters into a text field and click Save",
         "Open a second browser tab, submit the identical record again, and click Save"],
        "Min: A. Max: 255 chars of lorem ipsum. Unicode: Тест Ω 你好 . Duplicate: identical primary-key values.",
        "Boundary-length submissions persist exactly as entered. Unicode / emoji round-trip through the detail view with the same code points. The duplicate attempt is rejected with HTTP 409 or a uniqueness-violation message instead of creating a second record."))
    idx[0] += 1

    return cases


def _crud_read_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["crud_read"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Load the list view with seeded data and compare cell values against the source ({action})",
        "User is authenticated. At least three seed records exist in the backing store.",
        ["Open the list view URL in the browser",
         "Count the rows rendered in the table body and compare with the seed count",
         "Read the first row top-to-bottom and compare each cell with the source record",
         "Scroll the horizontal axis (or widen the viewport) and confirm every declared column header is visible",
         "Locate the first date cell and confirm the format matches the documented locale (e.g. YYYY-MM-DD)",
         "Click the next-page control and confirm the URL gains a page parameter and the table swaps to the next slice"],
        "At least three seeded records with varied dates, numbers and currency values.",
        "The row count matches the seed count exactly. Every declared column header is present. Date, number and currency cells render in the documented format. Pagination advances the URL and the table body, and the page-number control reflects the new page."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Load the list view with zero rows and confirm the empty state is rendered ({action})",
        "User is authenticated. No records exist for this view (fresh tenant or filtered to zero).",
        ["Open the list view URL in the browser",
         "Scan the page for the empty-state element (icon + message + call-to-action)",
         "Open DevTools → Console and confirm no red errors were logged",
         "Inspect the layout — the Header, Footer and sidebars are still present and aligned"],
        "",
        "A dedicated empty-state block is rendered with an explanatory message. No JavaScript errors appear in the console. The page chrome (Header, Footer, navigation) remains laid out; no ghost rows or skeleton loaders are stuck on screen."))
    idx[0] += 1

    return cases


def _crud_update_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["crud_update"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Edit an existing record, save, and confirm the change round-trips through the detail view ({action})",
        "User is authenticated. A known record exists and its current values are captured.",
        ["Click the target row in the list view to open the detail view",
         "Click the Edit button",
         "Confirm each form field is pre-populated with the existing value",
         "Change at least one field to a new valid value and note the exact new value",
         "Click Save",
         "Reload the detail view via the browser refresh control",
         "Compare every field with the notes taken before the edit and with the new value entered"],
        "A new valid value for one field, different from the current stored value.",
        "The PUT / PATCH request returns HTTP 200. The success toast references the updated record. After reload the edited field shows the new value, every other field is unchanged, and the updated_at timestamp has advanced."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Attempt to save invalid or missing data and confirm the original values are preserved ({action})",
        "User is authenticated. The edit form of an existing record is open.",
        ["Clear a required field and click Save",
         "Enter a malformed value (e.g. bad email format) into a validated field and click Save",
         "Leave the form open, navigate back to the list view, then reopen the same record"],
        "Empty value for a required field. Malformed email: notvalid.",
        "The server returns HTTP 400 / 422 or the client blocks submission. An inline error identifies the failing field. When the record is reopened from the list view its fields match the pre-edit values, confirming no partial write reached the store."))
    idx[0] += 1

    return cases


def _crud_delete_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["crud_delete"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Delete an existing record through the confirmation dialog and confirm it no longer appears ({action})",
        "User is authenticated. A known record exists (id recorded).",
        ["Open the list view",
         "Note the row count in the table footer / pagination summary",
         "Click the target row to open the detail view",
         "Click the Delete button",
         "Click Confirm in the modal dialog",
         "Wait for the redirect back to the list view",
         "Search the list for the deleted record id",
         "Try to open the detail URL of the deleted record directly in the address bar"],
        "",
        "The DELETE request returns HTTP 200 or 204. The row count decreases by one. A confirmation toast is displayed. Searching for the deleted id yields no results. Opening its detail URL returns HTTP 404 (or the configured not-found view)."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Open the delete confirmation dialog, click Cancel, and confirm the record is untouched ({action})",
        "User is authenticated. The delete confirmation modal is visible for a known record.",
        ["Click the Cancel button (or the close-X control) on the confirmation modal",
         "Verify the modal closes without issuing a network request (check DevTools → Network)",
         "Open the same record from the list view",
         "Compare every field with the pre-cancel values"],
        "",
        "No DELETE request is sent. The record is still present in the list view and the detail view shows the original field values with an unchanged updated_at."))
    idx[0] += 1

    return cases


def _search_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["search"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Search for a known seeded term and compare the returned rows against expectations ({action})",
        "User is authenticated. A seed record exists whose title/name contains the known term.",
        ["Click the search input in the Header / toolbar",
         "Enter the known term exactly as stored",
         "Press Enter or click the Search button",
         "Count the rows in the result table and compare with the pre-computed expected count",
         "Read the first result row and confirm the term is present in the expected column"],
        "Search term: a substring that appears in exactly one seeded record.",
        "The request returns HTTP 200 within 2 s. The result count shown in the UI equals the expected count. Each returned row contains the search term in at least one displayed column. The query is reflected in the URL so the result set is shareable."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Search for a term that does not exist and confirm the empty-results state is shown ({action})",
        "User is authenticated. Search bar is visible.",
        ["Click the search input",
         "Enter a string that is guaranteed not to exist in the dataset",
         "Press Enter",
         "Observe the results area and any suggestion text"],
        "Search term: xyznonexistent123.",
        "Zero rows are rendered. An explicit 'No results' message is shown in place of the table. No red error banner or console error appears. The URL still carries the query so the empty state is bookmarkable."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Submit unusual payloads to the search input and inspect how they are handled ({action})",
        "User is authenticated. Search bar is visible.",
        ["Enter a string of special characters into the search input and press Enter",
         "Paste a 500-character string into the search input and press Enter",
         "Enter the SQL-injection payload into the search input and press Enter",
         "Clear the input entirely and press Enter"],
        "Special: !@#$%^&*  |  Long: 500+ chars  |  SQL: ' OR 1=1 --",
        "Each query returns within the timeout with HTTP 200 or 400. The long string is either accepted or rejected with a length-limit message; the server does not 500. The SQL payload is treated as literal text and does not return the full dataset. The empty query either shows the full list or an explicit prompt; no stack trace is shown."))
    idx[0] += 1

    return cases


def _payment_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["payment"]
    action = _short(story.action)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Complete a checkout with a test-mode approved card and verify the order + receipt ({action})",
        "User is authenticated. Cart contains at least one item with a known price. Payment gateway is in test mode.",
        ["Click the cart icon in the Header to open the cart view",
         "Note the displayed subtotal, tax and grand total",
         "Click the Checkout button",
         "Enter the gateway test card number, expiry and CVC into the payment form",
         "Click Pay / Place Order",
         "Wait for the redirect to the order-confirmation page",
         "Compare the amount on the confirmation page with the grand total noted earlier",
         "Open the gateway dashboard (or the orders admin) and locate the transaction id"],
        "Test card: 4242 4242 4242 4242. Expiry: 12/28. CVC: 123.",
        "The POST /checkout request returns HTTP 200 with an order id. The confirmation page shows the same grand total the cart displayed. The receipt email (if configured) is queued. The gateway records exactly one authorisation for the expected amount."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Attempt checkout with a declined test card and confirm the cart is preserved ({action})",
        "User is authenticated. Checkout page is open with a populated cart. Payment gateway is in test mode.",
        ["Enter the declined test card number, any valid expiry, and any CVC into the payment form",
         "Click Pay / Place Order",
         "Inspect the error banner rendered on the checkout page",
         "Click the cart icon in the Header and verify the line items and totals"],
        "Declined test card: 4000 0000 0000 0002. Expiry: 12/28. CVC: 123.",
        "The gateway response is surfaced as a red error banner stating the card was declined, without leaking raw gateway codes or stack traces. The cart contents and totals are unchanged, so the user can retry with a different card."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Interrupt the payment request and verify no duplicate charge occurs on retry ({action})",
        "User is authenticated. Checkout page is open. DevTools is open to throttle / block the payment request.",
        ["Enter valid test card details into the payment form",
         "Open DevTools \u2192 Network and set the payment endpoint to Offline",
         "Click Pay / Place Order and wait for the client timeout",
         "Re-enable the Network and click Pay / Place Order a second time",
         "Open the gateway dashboard and count authorisations for this order",
         "Compare the order status in the admin with the charge state in the gateway"],
        "Test card: 4242 4242 4242 4242.",
        "Exactly one authorisation exists in the gateway dashboard. The order status in the admin matches the charge state (both paid, or both unpaid). The user never sees a 500 page; the retry either succeeds or is rejected with an idempotency-replay message.",
        comment="Critical edge case \u2014 pair with a gateway-logs audit after each release."))
    idx[0] += 1

    return cases


def _generic_tests(sn: int, story: UserStory, idx: list[int]) -> list[TestCase]:
    prefix, section = _SECTION_PREFIXES["generic"]
    action = _short(story.action)
    story_text = _short(story.original_text, 140)
    cases = []

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Positive",
        f"Exercise the happy path for: {action}",
        f"System is reachable. If the feature needs authentication, the user is logged in. Relevant seed data exists per the story: {story_text}",
        ["Open the entry point referenced by the story (page, menu item or API endpoint)",
         f"Perform the action described by the story: {_short(story.action, 80)}",
         "Capture the network response code and body via DevTools \u2192 Network",
         "Observe the UI change that the story promises (new row, toast, navigation, updated counter)"],
        "",
        f"The action returns HTTP 2xx. The UI change promised by the story is visible without a page reload. The backing store reflects the change on a subsequent read. Story under test: {story_text}"))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Negative",
        f"Drive the feature with invalid or missing input and confirm the rejection is explicit ({action})",
        "System is reachable. Feature entry point is open.",
        ["Leave a required field empty (or omit a required parameter) and trigger the action",
         "Supply a malformed value (wrong type, out-of-range number, bad email format) and trigger the action",
         "Inspect the HTTP response code and the rendered error message for each attempt"],
        "Empty required field. Malformed value for a typed field.",
        "Each invalid attempt returns HTTP 400 / 422 (or is blocked client-side before the network request). The error message names the failing field and the rule that was violated. No partial write reaches the backing store."))
    idx[0] += 1

    cases.append(_make_tc(sn, idx[0], section, prefix, story, "Edge Case",
        f"Push boundary, Unicode, and concurrent inputs through the feature ({action})",
        "System is reachable. Feature entry point is open.",
        ["Submit the documented minimum value (0, 1 or an empty-but-allowed payload) and capture the response",
         "Submit the documented maximum value (max-length string, max-allowed number) and capture the response",
         "Submit a Unicode-heavy payload (Cyrillic, CJK, emoji) and reopen the record",
         "Open a second browser session and trigger the same action at the same time from both sessions"],
        "Min: 0 / A. Max: documented upper bound. Unicode: Тест Ω 你好 . Concurrency: same payload from two sessions.",
        "Min and max values persist exactly as entered. Unicode round-trips through the detail view with matching code points. Concurrent submissions either both succeed with distinct ids or the second is rejected with a conflict message; the store never ends up in a half-written state."))
    idx[0] += 1

    return cases


# ── Scenario → generator mapping ─────────────────────────────────

_GENERATORS = {
    "auth": _auth_tests,
    "crud_create": _crud_create_tests,
    "crud_read": _crud_read_tests,
    "crud_update": _crud_update_tests,
    "crud_delete": _crud_delete_tests,
    "search": _search_tests,
    "payment": _payment_tests,
    "upload": _generic_tests,
    "export": _generic_tests,
    "notification": _generic_tests,
    "security": _generic_tests,
    "performance": _generic_tests,
    "integration": _generic_tests,
    "generic": _generic_tests,
}


# ── Custom prompt parsing ────────────────────────────────────────

# Vocabulary that maps prompt mentions (EN + UA) to canonical testing
# types. The keys are the canonical labels we tag on TCs / checklist
# items; the values are the substrings that, when found in the prompt,
# request that type explicitly.
_TESTING_TYPE_KEYWORDS: dict[str, tuple[str, ...]] = {
    "Functional":      ("functional", "функціональн", "функционал"),
    "Smoke":           ("smoke", "смок", "смоук", "smoke test"),
    "Sanity":          ("sanity", "саніті"),
    "Regression":      ("regression", "регрес", "регрешн"),
    "Performance":     ("performance", "speed", "load time", "продуктивн", "перформанс"),
    "Security":        ("security", "безпек", "secure"),
    "Accessibility":   ("accessibility", "a11y", "доступн", "wcag", "screen reader"),
    "Usability":       ("usability", "ux test", "юзабіліт", "юзабилит"),
    "UI/UX":           ("ui/ux", "ui test", "uxtest", "інтерфейс", "интерфейс"),
    "SEO":             ("seo", "сео", "search engine optim"),
    "Localization":    ("localization", "localisation", "i18n", "l10n", "локаліз", "локализ"),
    "Compatibility":   ("compatibility", "cross-browser", "cross browser",
                        "device matrix", "сумісніс", "совмести"),
    "API":             ("api test", "rest test", "api тест"),
    "E&E":             ("end-to-end", "end to end", "e2e", "e&e"),
    "Exploratory":     ("exploratory", "exploratory test", "досліджувальн"),
}


def _parse_testing_types(custom_prompt: str) -> tuple[list[str], bool]:
    """Detect testing-type narrowing in the custom prompt.

    Returns ``(types, is_narrowed)``:
      * ``types``       - canonical type labels mentioned in the prompt
      * ``is_narrowed`` - True only when the prompt explicitly narrows
        scope (e.g. "smoke only", "только перформанс"). When the prompt
        merely *mentions* types alongside other content, we keep the
        full default scope so the user gets comprehensive regression
        coverage by default.
    """
    if not custom_prompt:
        return ([], False)
    lower = custom_prompt.lower()

    found: list[str] = []
    for canonical, kws in _TESTING_TYPE_KEYWORDS.items():
        if any(kw in lower for kw in kws):
            found.append(canonical)

    # Narrowing markers — same word in any of the supported languages.
    # Operator video prompted "smoke (тільки основний функціонал)" and
    # "e2e (критичний функціонал)" — the parenthetical hints carry the
    # narrowing intent, so we also recognise "критичн", "core",
    # "essential", "main", "основн" as narrowing flags.
    NARROW_TOKENS = ("only", "лише", "тільки", "только", "focus on",
                     "фокус на", "перевір лише", "проверь только",
                     "just ", "exclusively",
                     "critical", "критичн", "критический",
                     "core ", "essential", "main functionality",
                     "основн функціонал", "основной функционал",
                     "основн functionality", "(core)", "(critical)",
                     "(critical functionality)")
    # Anti-narrowing markers — when present they explicitly request the
    # FULL set even though a testing-type keyword is in the prompt
    # (e.g. "regression — full coverage" mentions Regression but should
    # NOT collapse the output).
    BROADEN_TOKENS = ("full coverage", "повне покриття", "полное покрытие",
                      "comprehensive", "all-encompassing")
    if any(tok in lower for tok in BROADEN_TOKENS):
        return (found, False)
    is_narrowed = bool(found) and any(tok in lower for tok in NARROW_TOKENS)
    return (found, is_narrowed)


def _detect_testing_type(*, summary: str, section: str, category: str) -> str:
    """Tag an existing TC/Check item with its dominant testing type.

    Heuristic, runs over the generated case after the area-specific
    generators have already populated section/category. Used so we can
    filter the output by user-requested testing type without touching
    every generator.
    """
    s = (summary or "").lower()
    sec = (section or "").lower()

    # Section name beats summary heuristics — most generators name the
    # section after the testing type they target.
    if "performance" in sec or "browser: performance" in sec:
        return "Performance"
    if "security" in sec:
        return "Security"
    if "accessibility" in sec:
        return "Accessibility"
    if "responsive" in sec:
        return "Compatibility"
    if "seo" in sec:
        return "SEO"
    if "usability" in sec or "ui / ux" in sec:
        return "Usability"
    if "localization" in sec:
        return "Localization"

    # Summary heuristics for cases not anchored by section name.
    if any(k in s for k in ("https", "csrf", "xss", "sql injection",
                              "secure", "encryption", "permissions")):
        return "Security"
    if any(k in s for k in ("3 seconds", "load time", "loaded slowly",
                              "loaded successfully", "ms", "performance")):
        return "Performance"
    if any(k in s for k in ("alt text", "keyboard navigation", "screen reader",
                              "wcag", "focus indicator", "accessib")):
        return "Accessibility"
    if any(k in s for k in ("responsive", "viewport", "375px", "768px",
                              "1280px", "tablet", "mobile viewport")):
        return "Compatibility"
    if any(k in s for k in ("meta description", "open graph", "og:",
                              "robots.txt", "sitemap.xml", "canonical")):
        return "SEO"
    if any(k in s for k in ("readable", "hover state", "focus state",
                              "above the fold", "primary call-to-action",
                              "user-friendly")):
        return "Usability"
    if any(k in s for k in ("translation", "language switch", "lang attribute",
                              "multilingual", "locale")):
        return "Localization"

    if (category or "").lower() == "security":
        return "Security"
    return "Functional"


def _parse_tc_prompt(custom_prompt: str) -> dict:
    """Parse custom prompt into directives for test case generation."""
    directives: dict = {
        "categories": None,       # e.g. ["Positive", "Negative"]
        "extra_scenarios": [],     # forced scenario types
        "testing_types": None,    # narrowing list, None = keep all (regression)
    }
    if not custom_prompt:
        return directives

    lower = custom_prompt.lower()

    # Filter by categories
    requested_cats = []
    if "positive" in lower and "only" in lower:
        requested_cats = ["Positive"]
    elif "negative" in lower and "only" in lower:
        requested_cats = ["Negative"]
    elif "security" in lower and ("only" in lower or "focus" in lower):
        requested_cats = ["Security"]
    else:
        if "positive" in lower:
            requested_cats.append("Positive")
        if "negative" in lower:
            requested_cats.append("Negative")
        if "edge" in lower or "boundary" in lower:
            requested_cats.append("Edge Case")
        if "security" in lower:
            requested_cats.append("Security")
    if requested_cats:
        directives["categories"] = requested_cats

    # Force extra scenarios
    scenario_keywords = {
        "auth": ["auth", "login", "register"],
        "security": ["security", "injection", "xss"],
        "payment": ["payment", "checkout"],
        "search": ["search", "filter"],
        "performance": ["performance", "load"],
    }
    for scenario, kws in scenario_keywords.items():
        if any(kw in lower for kw in kws):
            directives["extra_scenarios"].append(scenario)

    # Testing-type narrowing — only kick in when the user explicitly
    # restricts scope (e.g. "smoke only"). Mere mentions are ignored
    # so the default behaviour stays comprehensive regression scope.
    types, is_narrowed = _parse_testing_types(custom_prompt)
    if is_narrowed and types:
        directives["testing_types"] = types

    # Free-form focus markers — "focus on forms", "тільки на формах",
    # "сфокусуйся на login flow", "тест-кейси для форм", "tests for
    # the login flow". When matched, we extract the focus phrase as
    # a list of keyword tokens; the generator drops every TC whose
    # summary/section/steps contain none of them.
    import re as _re
    _FOCUS_RE = _re.compile(
        r"(?:focus(?:\s+(?:on|только|лише|тільки))?|"
        r"тільки\s+на|лише\s+на|сфокусуйся\s+на|сосредоточь(?:ся)?\s+на|"
        r"only\s+on|just\s+on|"
        # Operator natural-language patterns (added 2026-05-02): the
        # prompt video literally said "написати тест-кейси для форм"
        # and "tests for the login flow". Recognise both.
        r"(?:test\s*cases?|tests|тест[-\s]?кейс[ии]?|чек[-\s]?лист[ии]?)\s+(?:for|для|про)|"
        r"написати\s+(?:тест[-\s]?кейс[ии]?|чек[-\s]?лист[ии]?)\s+(?:для|про)|"
        r"generate\s+(?:test\s*cases?|tests|checklist[s]?)\s+for"
        r")\s+(.+?)(?:[\.\!\?\n]|$)",
        _re.IGNORECASE,
    )

    # Per-field fan-out trigger: "all fields", "every field", "усі
    # поля", "кожне поле", "with all fields", "з усіма полями" — when
    # present alongside a forms-focus, the generator emits one TC per
    # detected form field instead of a single "submit form" case.
    _ALL_FIELDS_RE = _re.compile(
        r"(?:all\s+fields|every\s+field|each\s+field|"
        r"all\s+inputs|each\s+input|"
        r"усі\s+поля|кожне\s+поле|кожне\s+з\s+полів|"
        r"all\s+form\s+fields|all\s+the\s+fields|"
        r"з\s+усіма\s+полями|з\s+кожним\s+полем|"
        r"per[-\s]?field|по\s+кожному\s+полю|"
        r"with\s+all\s+fields)",
        _re.IGNORECASE,
    )
    if _ALL_FIELDS_RE.search(custom_prompt):
        directives["expand_fields"] = True
    # Strip the matched phrase so the focus tokenizer sees a clean
    # noun phrase ("login flow" instead of "login flow with all
    # fields").
    custom_prompt_clean = _ALL_FIELDS_RE.sub(" ", custom_prompt)
    focus_tokens: list[str] = []
    # Drop any URL fragment from the focus phrase before tokenisation;
    # otherwise a host like "testfort.com" leaks "testfort" into the
    # keyword list and over-narrows the kept TCs.
    _URL_STRIP_RE = _re.compile(r"https?://\S+|\b\w+\.[a-z]{2,}\b",
                                _re.IGNORECASE)
    for m in _FOCUS_RE.finditer(custom_prompt_clean):
        phrase = (m.group(1) or "").strip()
        phrase = _URL_STRIP_RE.sub(" ", phrase)
        # Split on common joiners so "forms, login" → ["form","login"].
        for tok in _re.split(r"[,/\s]+", phrase):
            tok = tok.strip().lower()
            if not tok or tok in {
                # English fillers
                "the", "a", "an", "and", "or", "i", "to", "in", "on",
                "for", "of", "with", "all", "any", "every", "each",
                "fields", "field", "input", "inputs",
                # Ukrainian / Russian fillers
                "усіма", "усі", "усе", "кожне", "кожен", "кожним",
                "полями", "поля", "поле", "полів",
                "та", "і", "й", "у", "в", "на", "до", "по", "з",
                "и", "или", "все", "каждый", "каждое", "поле",
            }:
                continue
            if len(tok) < 3:
                continue
            # Drop bare URLs — the URL itself is fed elsewhere as a
            # requirement; carrying it through as a keyword filter
            # would discard every TC that doesn't literally name the
            # domain.
            if tok.startswith("http") or "." in tok:
                continue
            focus_tokens.append(tok)
    if focus_tokens:
        directives["focus_tokens"] = list(dict.fromkeys(focus_tokens))[:6]

    return directives


# ── Public API ───────────────────────────────────────────────────



def _generate_per_field_cases(analysis, *, next_section: int,
                              section_map: dict, section_counters: dict
                              ) -> list:
    """Fan-out form coverage by emitting one TC per detected input.

    For every (page, form, field) tuple that the crawler captured we
    produce three cases: required-validation, valid-input,
    boundary-overflow. The result is appended to the existing pack;
    section "Forms — Fields" gets its own section number so the
    output is grouped predictably in the UI.
    """
    out: list = []
    pages = getattr(analysis, "site_pages", None) or []
    if not pages:
        return out

    section = "Forms — Fields"
    if section not in section_map:
        section_map[section] = next_section
        section_counters[next_section] = 1
        next_section += 1

    sn = section_map[section]

    def _new_id() -> str:
        idx = section_counters[sn]
        tc_id = f"SC{sn}_{idx:03d}"
        section_counters[sn] = idx + 1
        return tc_id

    for page in pages:
        forms = page.get("forms") or []
        page_url = page.get("url") or ""
        for f_ix, form in enumerate(forms, start=1):
            fields = form.get("fields") or form.get("inputs") or []
            for field in fields:
                if isinstance(field, dict):
                    name = (field.get("name") or field.get("placeholder")
                            or field.get("label") or field.get("id")
                            or f"field-{f_ix}")
                    ftype = (field.get("type") or "text").lower()
                else:
                    name = str(field) or f"field-{f_ix}"
                    ftype = "text"
                base = {
                    "preconditions": (
                        f"User on {page_url}; form #{f_ix} is visible"
                        if page_url else f"Form #{f_ix} is visible"
                    ),
                    "test_data": f"Field: '{name}' (type={ftype})",
                    "category": "Negative",
                    "priority": "High",
                }
                # 1) required-validation: leave field empty, fill rest.
                out.append(TestCase(
                    id=_new_id(), section=section, section_num=sn,
                    summary=f"Verify '{name}' field rejects empty input "
                            f"and shows validation error",
                    preconditions=base["preconditions"],
                    test_steps=(
                        f"1. Open the page with form\n"
                        f"2. Fill every field except '{name}'\n"
                        f"3. Submit the form\n"
                        f"4. Inspect the response and the field"),
                    test_data=base["test_data"],
                    expected_result=(
                        f"The form does not submit. An inline validation "
                        f"error is displayed next to '{name}' or summarised "
                        f"at the top. Focus is moved to the offending "
                        f"field."),
                    category="Negative", priority="High",
                ))
                # 2) valid input — type-aware.
                if ftype in ("email",):
                    valid = "tester@example.com"
                    bad = "tester@"
                elif ftype in ("tel", "phone"):
                    valid = "+380501234567"
                    bad = "+38050"
                elif ftype in ("url", "website"):
                    valid = "https://example.com"
                    bad = "ht!ps://"
                elif ftype in ("number"):
                    valid = "42"
                    bad = "abc"
                elif ftype in ("password",):
                    valid = "Str0ngP@ss!2026"
                    bad = "1"
                else:
                    valid = "Sample input value 123"
                    bad = ""
                out.append(TestCase(
                    id=_new_id(), section=section, section_num=sn,
                    summary=f"Verify '{name}' field accepts a valid value "
                            f"and clears errors",
                    preconditions=base["preconditions"],
                    test_steps=(
                        f"1. Open the page with form\n"
                        f"2. Type a valid value into '{name}': {valid}\n"
                        f"3. Tab away from the field"),
                    test_data=f"{base['test_data']}; valid={valid!r}",
                    expected_result=(
                        f"Any prior validation error on '{name}' clears. "
                        f"The submit button becomes enabled when all "
                        f"required fields are filled."),
                    category="Positive", priority="High",
                ))
                # 3) Boundary overflow — type-aware.
                if ftype in ("email",):
                    overflow = "a" * 250 + "@x.com"
                elif ftype == "number":
                    overflow = "9" * 12
                else:
                    overflow = "X" * 1024
                out.append(TestCase(
                    id=_new_id(), section=section, section_num=sn,
                    summary=f"Verify '{name}' enforces a sensible max "
                            f"length / value",
                    preconditions=base["preconditions"],
                    test_steps=(
                        f"1. Open the page with form\n"
                        f"2. Paste an oversized value into '{name}': "
                        f"{len(overflow)} chars\n"
                        f"3. Submit the form"),
                    test_data=f"{base['test_data']}; overflow_len="
                             f"{len(overflow)}",
                    expected_result=(
                        f"The field either rejects the input client-side "
                        f"(maxlength enforced, error shown) or the server "
                        f"rejects with a 4xx and a clear message. No "
                        f"silent truncation, no 500."),
                    category="Negative", priority="High",
                ))
    return out


def generate_test_cases(stories: list[UserStory], custom_prompt: str = "",
                        raw_requirements: list[dict] | None = None) -> list[TestCase]:
    """Generate professional test cases using QA persona.

    The Senior QA Engineer persona analyzes input to determine testing areas
    and generates domain-specific test cases from the ISTQB knowledge base,
    then supplements with story-specific cases for any requirements not
    covered by the knowledge base.
    """
    from .qa_persona import (analyze_input, generate_professional_test_cases,
                             is_instruction)

    # Build requirements list for the persona
    reqs = raw_requirements or []
    if not reqs and stories:
        reqs = [{"text": s.original_text} for s in stories]

    # Filter out instruction lines
    reqs = [r for r in reqs if not is_instruction(r.get("text", ""))]

    analysis = analyze_input(reqs, custom_prompt)
    pro_templates = generate_professional_test_cases(analysis, stories, custom_prompt)

    # Convert TCTemplate → TestCase with TestFort IDs
    all_cases: list[TestCase] = []
    section_map: dict[str, int] = {}  # section_name → section_num
    section_counters: dict[int, int] = {}  # section_num → next idx
    next_section = 1

    directives = _parse_tc_prompt(custom_prompt)

    for tmpl in pro_templates:
        section = tmpl.section or "General"
        if section not in section_map:
            section_map[section] = next_section
            section_counters[next_section] = 1
            next_section += 1

        sn = section_map[section]
        idx = section_counters[sn]
        tc_id = f"SC{sn}_{idx:03d}"
        section_counters[sn] = idx + 1

        steps_text = "\n".join(f"{i+1}. {s}" for i, s in enumerate(tmpl.steps))
        # Tag each TC with its dominant testing type. We honour the
        # template's own ``testing_type`` when set (e.g. SEO / Usability /
        # Localization generators set it explicitly); otherwise we fall
        # back to a section/summary heuristic so older generators still
        # get correct labels without code changes per generator.
        tt = getattr(tmpl, "testing_type", "") or _detect_testing_type(
            summary=tmpl.summary, section=tmpl.section, category=tmpl.category,
        )
        tc = TestCase(
            id=tc_id, section=section, section_num=sn,
            summary=tmpl.summary, preconditions=tmpl.preconditions,
            test_steps=steps_text, test_data=tmpl.test_data,
            expected_result=tmpl.expected_result,
            category=tmpl.category, priority=tmpl.priority,
        )
        # Stash testing_type on the TC so exporters / UI / filters can
        # pick it up. Older code paths that read TestCase as a dataclass
        # won't break — getattr with default keeps back-compat.
        try:
            tc.testing_type = tt
        except Exception:
            pass
        all_cases.append(tc)

    # Apply custom prompt category filter
    if directives["categories"]:
        all_cases = [tc for tc in all_cases if tc.category in directives["categories"]]

    # Apply custom-prompt testing-type narrowing. When the prompt asks
    # for "smoke only" / "performance focus" / "тільки security", we
    # keep just the matching scope. Otherwise (default) the full
    # regression-scope set passes through unchanged.
    if directives.get("testing_types"):
        wanted = set(directives["testing_types"])
        all_cases = [tc for tc in all_cases if getattr(tc, "testing_type", "Functional") in wanted]

    # Free-form focus filter — "focus on forms / login flow / тільки
    # на формах" keeps only TCs whose summary, section, steps, or
    # expected_result mention any focus token. Saves a round-trip
    # back to the generator for the operator who wants targeted runs
    # without re-typing requirements.
    if directives.get("focus_tokens"):
        toks = [t for t in directives["focus_tokens"] if t]
        if toks:
            def _hit(tc):
                blob = " ".join((
                    tc.summary or "", tc.section or "",
                    tc.test_steps or "", tc.expected_result or "",
                    tc.preconditions or "", tc.test_data or "",
                )).lower()
                return any(tok in blob for tok in toks)
            kept = [tc for tc in all_cases if _hit(tc)]
            # Don't empty the list out completely — if nothing matched,
            # fall back to the full set so the operator still sees
            # something. We log this implicitly by flag-only behaviour.
            if kept:
                all_cases = kept

    # Per-field fan-out (Feature: "test cases for forms with all
    # fields"). When the prompt asked for it AND the persona's site
    # crawler captured form structures, emit one TC per detected
    # field — empty value, valid value, boundary value — so the
    # output covers each input rather than the single "submit form"
    # case that comes out of the canned templates.
    if directives.get("expand_fields"):
        from .qa_persona import analyze_input as _re_analyze
        try:
            extra_cases = _generate_per_field_cases(
                analysis,
                next_section=next_section,
                section_map=section_map,
                section_counters=section_counters,
            )
        except Exception as exc:
            extra_cases = []
        if extra_cases:
            all_cases.extend(extra_cases)

    # QA Team Lead review — validate and auto-fix documentation quality
    from .qa_team_lead import review_test_cases
    all_cases, _review_report = review_test_cases(all_cases)

    return all_cases


def generate_checklist(stories: list[UserStory], custom_prompt: str = "",
                       raw_requirements: list[dict] | None = None) -> list[ChecklistItem]:
    """Generate a professional low-level checklist using QA persona.

    The Senior QA Engineer persona analyzes input to determine testing areas
    and generates domain-specific checks from the ISTQB knowledge base.
    """
    from .qa_persona import analyze_input, generate_professional_checklist, is_instruction

    # Build requirements list for the persona
    reqs = raw_requirements or []
    if not reqs and stories:
        reqs = [{"text": s.original_text} for s in stories]

    # Filter out instruction lines
    reqs = [r for r in reqs if not is_instruction(r.get("text", ""))]

    analysis = analyze_input(reqs, custom_prompt)
    pro_items = generate_professional_checklist(analysis, custom_prompt)

    # Convert to ChecklistItem with TestFort IDs
    items: list[ChecklistItem] = []
    prefix_counters: dict[str, int] = {}
    from .qa_knowledge_loader import LOADER

    directives = _parse_tc_prompt(custom_prompt)
    for item in pro_items:
        prefix = LOADER.get_section_prefix(item.section) or "GEN"
        if prefix not in prefix_counters:
            prefix_counters[prefix] = 1
        counter = prefix_counters[prefix]

        tt = getattr(item, "testing_type", "") or _detect_testing_type(
            summary=item.objective, section=item.section, category=item.category,
        )
        cl_item = ChecklistItem(
            id=f"{prefix}_{counter:03d}",
            section=item.section,
            objective=item.objective,
            category=item.category,
            priority=item.priority,
        )
        try:
            cl_item.testing_type = tt
        except Exception:
            pass
        items.append(cl_item)
        prefix_counters[prefix] = counter + 1

    # Apply custom-prompt testing-type narrowing — same semantics as
    # in generate_test_cases. Default scope is full regression coverage.
    if directives.get("testing_types"):
        wanted = set(directives["testing_types"])
        items = [it for it in items if getattr(it, "testing_type", "Functional") in wanted]

    # QA Team Lead review — validate and auto-fix documentation quality
    from .qa_team_lead import review_checklist
    items, _review_report = review_checklist(items)

    return items


def generate_traceability(stories: list[UserStory], test_cases: list[TestCase]) -> list[dict]:
    """Build traceability: Requirement -> User Story -> Test Cases."""
    matrix = []
    for story in stories:
        linked = [tc for tc in test_cases if tc.user_story_id == story.id]
        matrix.append({
            "requirement_id": story.requirement_id,
            "user_story_id": story.id,
            "user_story": f"As a {story.role}, I want {_short(story.action, 80)}",
            "priority": story.priority,
            "test_case_ids": [tc.id for tc in linked],
            "test_count": len(linked),
            "categories": sorted(set(tc.category for tc in linked)),
        })
    return matrix
