"""
TestFortge — Test Credentials

Shared model for test-account credentials used by both Test Execution and
Automation QA modules.

Two modes are supported:

* **provided**   — QA engineer types in an existing username/password that
                   must be used to reach the part of the site that tests
                   actually need (e.g. an admin area, a paid-tier account).

* **generated**  — TestForTge generates a throw-away test account on the
                   fly so the engineer doesn't need to hand-craft one.
                   If a registration URL is supplied, the automation
                   runner can auto-register before testing; otherwise the
                   generated pair is surfaced to the engineer to create
                   the account manually.
"""
from __future__ import annotations

import random
import secrets
import string
import time
from dataclasses import dataclass, field, asdict
from typing import Optional


@dataclass
class TestCredentials:
    """Credentials and related URLs used to authenticate during a test run."""
    mode: str = "none"                 # "none" | "provided" | "generated"
    login_url: str = ""                # login page URL (optional)
    username: str = ""                 # email or username
    password: str = ""                 # plain-text (session-only, never logged)
    # Optional registration hints (used only when mode == "generated")
    register_url: str = ""
    display_name: str = ""             # friendly handle e.g. "TestForTge Tester"
    notes: str = ""                    # free-form notes shown on the result page

    # Selector hints so the automation runner can find the form fields
    # without relying on heuristics. Empty strings = use role/placeholder
    # heuristics.
    username_selector: str = ""
    password_selector: str = ""
    submit_selector: str = ""

    def is_active(self) -> bool:
        """True when the run should actually attempt to authenticate."""
        return self.mode in ("provided", "generated") and bool(
            self.username or self.mode == "generated"
        )

    def as_public_dict(self) -> dict:
        """Return a dict safe for templates (omits raw password)."""
        d = asdict(self)
        d["password"] = "********" if self.password else ""
        return d


# ── Random test account generator ─────────────────────────────────

_ADJ = ["happy", "brave", "quick", "silent", "sunny", "clever", "lucky",
        "nimble", "witty", "sharp", "calm", "bold", "kind", "eager"]
_NOUN = ["otter", "tiger", "sparrow", "panda", "falcon", "koala", "badger",
         "dolphin", "fox", "hawk", "wolf", "owl", "lynx", "bear"]


def _random_password(length: int = 14) -> str:
    """A strong password with lower/upper/digit/symbol. No ambiguous chars."""
    alphabet = (
        "ABCDEFGHJKLMNPQRSTUVWXYZ"  # no I, O
        "abcdefghjkmnpqrstuvwxyz"    # no i, l, o
        "23456789"                   # no 0, 1
        "!@#$%^&*?"
    )
    # Ensure at least one of each class
    req = ["A", "b", "3", "@"]
    extra = [secrets.choice(alphabet) for _ in range(length - len(req))]
    pw = req + extra
    random.shuffle(pw)
    return "".join(pw)


def _random_handle() -> str:
    return f"{random.choice(_ADJ)}-{random.choice(_NOUN)}-{random.randint(100, 999)}"


def generate_test_account(base_domain: str = "testfortge.test",
                          register_url: str = "",
                          login_url: str = "") -> TestCredentials:
    """Produce a fresh, throw-away test account.

    The email uses a local-part with a millisecond timestamp so successive
    calls never collide. The password is strong but human-readable.
    """
    handle = _random_handle()
    ts = int(time.time() * 1000)
    # Strip scheme/path from base_domain if a URL was passed by mistake
    domain = base_domain
    if "://" in domain:
        domain = domain.split("://", 1)[1].split("/", 1)[0]
    if not domain or " " in domain:
        domain = "testfortge.test"

    email = f"qa.{handle}.{ts}@{domain}"
    pw = _random_password()

    return TestCredentials(
        mode="generated",
        login_url=login_url,
        register_url=register_url,
        username=email,
        password=pw,
        display_name=f"TestForTge — {handle}",
        notes="Throw-away account generated by TestForTge for this test run.",
    )


# ── Session (de)serialization ─────────────────────────────────────

_KEYS = ("mode", "login_url", "username", "password",
         "register_url", "display_name", "notes",
         "username_selector", "password_selector", "submit_selector")


def credentials_from_form(form, prefix: str = "") -> TestCredentials:
    """Build a TestCredentials from a Flask request.form-like mapping."""
    def g(k: str) -> str:
        return (form.get(prefix + k, "") or "").strip()

    mode = g("cred_mode") or "none"
    if mode not in ("none", "provided", "generated"):
        mode = "none"

    cred = TestCredentials(
        mode=mode,
        login_url=g("cred_login_url"),
        username=g("cred_username"),
        password=form.get(prefix + "cred_password", "") or "",  # preserve spaces
        register_url=g("cred_register_url"),
        display_name=g("cred_display_name"),
        notes=g("cred_notes"),
        username_selector=g("cred_username_selector"),
        password_selector=g("cred_password_selector"),
        submit_selector=g("cred_submit_selector"),
    )

    # If the user asked for generation and left username/password blank,
    # fill them in automatically now.
    if cred.mode == "generated" and (not cred.username or not cred.password):
        gen = generate_test_account(
            register_url=cred.register_url,
            login_url=cred.login_url,
        )
        cred.username = cred.username or gen.username
        cred.password = cred.password or gen.password
        cred.display_name = cred.display_name or gen.display_name
        cred.notes = cred.notes or gen.notes

    return cred


def credentials_to_session(cred: TestCredentials) -> dict:
    """Serialize into a plain dict suitable for Flask session storage."""
    return {k: getattr(cred, k) for k in _KEYS}


def credentials_from_session(data: dict | None) -> TestCredentials:
    """Inverse of :func:`credentials_to_session`. Safe on missing keys."""
    data = data or {}
    return TestCredentials(**{k: data.get(k, "") for k in _KEYS})
